services:
  - type: web
    name: baos-album-backend
    env: node
    plan: free
    envVars:
      - key: MONGO_URI
        value: mongodb+srv://baosum01:Giabao0905@cluster0.gw9dg.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0

